const axios = require('axios');
const alimtalk = require('./lib/alimtalk');
const sendnumber = require('./lib/alimtalk.sendnumber');

/**
 * Config setting
 *
 * @param {string} clientId apistore's id
 * @param {string} authKey Authentication key generated by apistore
 */
function factory(clientId, authKey) {
  api = axios.create({
    baseURL: 'http://api.apistore.co.kr/kko',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'x-waple-authorization': authKey,
    },
  });

  return {
    alimtalk: alimtalk(clientId, api),
    sendnumber: sendnumber(clientId, api),
  };
}

module.exports = factory;
